stages:
  data_splitting:
    cmd: python src/data/data_splitting.py
    deps:
    - data/raw_data/raw.csv
    - src/data/data_splitting.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  data_normalization:
    cmd: python src/data/data_normalize.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/data_normalize.py
    outs:
    - data/processed_data/X_test_scale.csv
    - data/processed_data/X_train_scale.csv
  best_parameters:
    cmd: python src/models/best_param.py
    deps:
    - data/processed_data/X_train_scale.csv
    - data/processed_data/y_train.csv
    - src/models/best_param.py
    outs:
    - models/best_params.pkl
  model_training:
    cmd: python src/models/training.py
    deps:
    - data/processed_data/X_train_scale.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/training.py
    outs:
    - models/model.pkl
